"""Backend tests for Ganu Denu money manager app"""
import pytest
import requests
import oshttps://vscode-bff28d21-c223-48fe-b879-d5b66e8a32a3.preview.emergentagent.com/
from datetime import datetime

BASE_URL = os.environ.get('EXPO_PUBLIC_BACKEND_URL', '').rstrip('/')

@pytest.fixture
def client():
    s = requests.Session()
        s.headers.update({"Content-Type": "application/json"})
            return s
            
            class TestHealth:
                """Health check"""
                    def test_api_root(self, client):
                            r = client.get(f"{BASE_URL}/api/")
                                    assert r.status_code == 200
                                            data = r.json()
                                                    assert "status" in data
                                                    
                                                    class TestTransactions:
                                                        """Transaction CRUD tests"""
                                                            created_id = None
                                                            
                                                                def test_get_transactions(self, client):
                                                                        r = client.get(f"{BASE_URL}/api/transactions")
                                                                                assert r.status_code == 200
                                                                                        data = r.json()
                                                                                                assert isinstance(data, list)
                                                                                                        print(f"Total transactions: {len(data)}")
                                                                                                        
                                                                                                            def test_get_transactions_with_month_filter(self, client):
                                                                                                                    now = datetime.now()
                                                                                                                            r = client.get(f"{BASE_URL}/api/transactions?month={now.month}&year={now.year}")
                                                                                                                                    assert r.status_code == 200
                                                                                                                                            data = r.json()
                                                                                                                                                    assert isinstance(data, list)
                                                                                                                                                            print(f"Current month transactions: {len(data)}")
                                                                                                                                                            
                                                                                                                                                                def test_create_transaction(self, client):
                                                                                                                                                                        payload = {
                                                                                                                                                                                    "amount": 500.00,
                                                                                                                                                                                                "category": "food",
                                                                                                                                                                                                            "description": "TEST_Backend Test Transaction",
                                                                                                                                                                                                                        "is_income": False,
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                        r = client.post(f"{BASE_URL}/api/transactions", json=payload)
                                                                                                                                                                                                                                                assert r.status_code == 200
                                                                                                                                                                                                                                                        data = r.json()
                                                                                                                                                                                                                                                                assert data["amount"] == 500.00
                                                                                                                                                                                                                                                                        assert data["category"] == "food"
                                                                                                                                                                                                                                                                                assert "id" in data
                                                                                                                                                                                                                                                                                        TestTransactions.created_id = data["id"]
                                                                                                                                                                                                                                                                                                print(f"Created transaction id: {data['id']}")
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    def test_create_income_transaction(self, client):
                                                                                                                                                                                                                                                                                                            payload = {
                                                                                                                                                                                                                                                                                                                        "amount": 10000,
                                                                                                                                                                                                                                                                                                                                    "category": "salary",
                                                                                                                                                                                                                                                                                                                                                "description": "TEST_Income Transaction",
                                                                                                                                                                                                                                                                                                                                                            "is_income": True,
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            r = client.post(f"{BASE_URL}/api/transactions", json=payload)
                                                                                                                                                                                                                                                                                                                                                                                    assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                            data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                    assert data["is_income"] == True
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        def test_create_sms_transaction(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                payload = {
                                                                                                                                                                                                                                                                                                                                                                                                                            "amount": 2000,
                                                                                                                                                                                                                                                                                                                                                                                                                                        "category": "transport",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": "TEST_SMS Transaction",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_income": False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "from_sms": True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "raw_sms": "BOC: Debit Rs.2000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "merchant": "Petrol Station"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r = client.post(f"{BASE_URL}/api/transactions", json=payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert data["from_sms"] == True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_delete_transaction(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not TestTransactions.created_id:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pytest.skip("No created transaction to delete")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r = client.delete(f"{BASE_URL}/api/transactions/{TestTransactions.created_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert data["success"] == True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_delete_nonexistent_transaction(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                r = client.delete(f"{BASE_URL}/api/transactions/nonexistent-id-12345")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert r.status_code == 404
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class TestStats:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Stats endpoint tests"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_get_stats(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        now = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                r = client.get(f"{BASE_URL}/api/stats?month={now.month}&year={now.year}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "income" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert "expenses" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "balance" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert "total_count" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "sms_count" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert "categories" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Stats - Income: {data['income']}, Expenses: {data['expenses']}, Balance: {data['balance']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_stats_balance_calculation(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    now = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r = client.get(f"{BASE_URL}/api/stats?month={now.month}&year={now.year}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert data["balance"] == data["income"] - data["expenses"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class TestTrends:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Trends endpoint tests"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_get_trends(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r = client.get(f"{BASE_URL}/api/stats/trends")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert isinstance(data, list)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert len(data) == 6  # 6 months
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for item in data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "month" in item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert "year" in item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert "label" in item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert "income" in item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "expenses" in item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Trends: {[t['label'] for t in data]}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class TestSeed:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Seed data test"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_seed_data(self, client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                r = client.post(f"{BASE_URL}/api/seed")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert r.status_code == 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert "seeded" in data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert data["seeded"] == 30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Seeded {data['seeded']} transactions")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """